In [2]:
import pickle
import cv2
import numpy as np

In [3]:
def undistort(img, cal_dir='cal_pickle.p'):
	#undistorting frame
    with open(cal_dir, mode='rb') as f:
        file = pickle.load(f)
    mtx = file['mtx']
    dist = file['dist']
    dst = cv2.undistort(img, mtx, dist, None, mtx)
    return dst

In [4]:
def colorFilter(img):
	#applying color filter for specific color(considering yellow and white color)
    hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
    lowerYellow = np.array([18,94,140]) 
    upperYellow = np.array([48,255,255])
    lowerWhite = np.array([0, 0, 200])
    upperWhite = np.array([255, 255, 255])
    maskedWhite= cv2.inRange(hsv,lowerWhite,upperWhite)
    maskedYellow = cv2.inRange(hsv, lowerYellow, upperYellow)
    combinedImage = cv2.bitwise_or(maskedWhite,maskedYellow)
    return combinedImage 


In [5]:
img = cv2.imread('test.jpg')
dst = undistort(img)
combinedImage,imgCanny, imgColor = thresholding(dst)

cv2.imshow('dst', dst)
# cv2.imshow('color', imgColor)
# cv2.imshow('erode', imgErode)
cv2.imshow('ths', combinedImage)

cv2.waitKey()
cv2.destroyAllWindows()

NameError: name 'thresholding' is not defined

In [6]:
def drawPoints(img, src):
	#drawing circles on frame
    img_size = np.float32([(img.shape[1],img.shape[0])])
    #src = np.float32([(0.43, 0.65), (0.58, 0.65), (0.1, 1), (1, 1)])
    src = src * img_size
    for x in range( 0,4): 
        cv2.circle(img,(int(src[x][0]),int(src[x][1])),10,(0,255,0),cv2.FILLED)
    return img

In [ ]:

img = cv2.imread('test.jpg')
# img = drawPoints(img, src)
# cv2.imshow('img', img)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [7]:
def perspective_warp(img,
                     dst_size=(1280, 720),
                     src=np.float32([(0.43,0.65),(0.58,0.65),(0.1,1),(1,1)]),
                     dst=np.float32([(0,0), (1, 0), (0,1), (1,1)])):
    img_size = np.float32([(img.shape[1],img.shape[0])])
    src = src* img_size
    # For destination points, I'm arbitrarily choosing some points to be
    # a nice fit for displaying our warped result
    # again, not exact, but close enough for our purposes
    dst = dst * np.float32(dst_size)
    # Given src and dst points, calculate the perspective transform matrix
    M = cv2.getPerspectiveTransform(src, dst)
    # Warp the image using OpenCV warpPerspective()
    warped = cv2.warpPerspective(img, M, dst_size)

    return warped

In [12]:
src = np.float32([(0.43, 0.65), (0.58, 0.65), (0.1, 1), (1, 1)])
img = cv2.imread('test.jpg')
warped = perspective_warp(img)
img = drawPoints(img, src)
cv2.imshow('warped', warped)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
def get_hist(img):
    hist = np.sum(img[img.shape[0]//2:,:], axis=0)
    return hist
hist = get_hist(img)
print(hist)

[[11485 11513 12401]
 [11584 11664 12526]
 [11768 11811 12704]
 ...
 [13218 16299 15594]
 [12873 16019 15260]
 [12980 16046 15341]]


In [14]:
print(np.empty(3))

[ 6.95246222e-310  1.35181193e-311 -0.00000000e+000]


In [6]:

img = cv2.imread('test.jpg')
print(img.shape)
out_img = np.dstack((img, img, img)) * 255
print(out_img.shape)
print((out_img[:,:,0:3]==out_img[:,:,3:6]).all())
# cv2.imshow('img', out_img)
# cv2.waitKey()
# cv2.destroyAllWindows()

(317, 563, 3)
(317, 563, 9)
True


In [1]:
import cv2

In [9]:
img = cv2.imread('./data/image/straight.jpg')
print(img.shape)

(317, 563, 3)
